"""Initial migration

Revision ID: f662571722fc
Revises: 
Create Date: 2025-11-19 08:56:09.949887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f662571722fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "symbol",
            sa.String(length=20),
            nullable=False,
            comment="Stock symbol (e.g., RELIANCE.NS)",
        ),
        sa.Column("isin", sa.String(length=12), nullable=True, comment="ISIN code (INE002A01018)"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Company name"),
        sa.Column("sector", sa.String(length=100), nullable=True, comment="Sector classification"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix_companies_isin"), "companies", ["isin"], unique=True)
    op.create_index(op.f("ix_companies_sector"), "companies", ["sector"], unique=False)
    op.create_index(op.f("ix_companies_symbol"), "companies", ["symbol"], unique=True)
    op.create_index("ix_companies_symbol_sector", "companies", ["symbol", "sector"], unique=False)
    op.create_table(
        "financials_annual",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False, comment="Fiscal year (e.g., 2023)"),
        sa.Column("revenue", sa.Float(), nullable=True, comment="Revenue in Crores"),
        sa.Column("profit", sa.Float(), nullable=True, comment="Net Profit in Crores"),
        sa.Column("roce", sa.Float(), nullable=True, comment="Return on Capital Employed (%)"),
        sa.Column("roe", sa.Float(), nullable=True, comment="Return on Equity (%)"),
        sa.Column("debt_equity", sa.Float(), nullable=True, comment="Debt to Equity ratio"),
        sa.Column("current_ratio", sa.Float(), nullable=True, comment="Current Ratio"),
        sa.Column("eps", sa.Float(), nullable=True, comment="Earnings Per Share"),
        sa.Column("book_value", sa.Float(), nullable=True, comment="Book Value Per Share"),
        sa.Column("dividend_yield", sa.Float(), nullable=True, comment="Dividend Yield (%)"),
        sa.Column(
            "cash_flow_operating",
            sa.Float(),
            nullable=True,
            comment="Operating Cash Flow in Crores",
        ),
        sa.Column(
            "cash_flow_investing",
            sa.Float(),
            nullable=True,
            comment="Investing Cash Flow in Crores",
        ),
        sa.Column(
            "cash_flow_financing",
            sa.Float(),
            nullable=True,
            comment="Financing Cash Flow in Crores",
        ),
        sa.Column(
            "raw_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Complete JSON from Screener.in",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financials_annual_company_id"), "financials_annual", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_financials_annual_fiscal_year"), "financials_annual", ["fiscal_year"], unique=False
    )
    op.create_index(
        "ix_financials_company_year",
        "financials_annual",
        ["company_id", "fiscal_year"],
        unique=True,
    )
    op.create_index("ix_financials_year", "financials_annual", ["fiscal_year"], unique=False)
    op.create_table(
        "financials_quarterly",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "quarter_date",
            sa.Date(),
            nullable=False,
            comment="Quarter ending date (e.g., 2023-12-31)",
        ),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("profit", sa.Float(), nullable=True),
        sa.Column("eps", sa.Float(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_financials_quarterly_company_date",
        "financials_quarterly",
        ["company_id", "quarter_date"],
        unique=True,
    )
    op.create_index(
        op.f("ix_financials_quarterly_company_id"),
        "financials_quarterly",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financials_quarterly_quarter_date"),
        "financials_quarterly",
        ["quarter_date"],
        unique=False,
    )
    op.create_table(
        "prices_ohlc",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False, comment="Trading date"),
        sa.Column("open", sa.Float(), nullable=False, comment="Opening price"),
        sa.Column("high", sa.Float(), nullable=False, comment="High price"),
        sa.Column("low", sa.Float(), nullable=False, comment="Low price"),
        sa.Column("close", sa.Float(), nullable=False, comment="Closing price"),
        sa.Column("volume", sa.Float(), nullable=True, comment="Trading volume"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prices_company_date", "prices_ohlc", ["company_id", "date"], unique=True)
    op.create_index("ix_prices_date", "prices_ohlc", ["date"], unique=False)
    op.create_index(op.f("ix_prices_ohlc_company_id"), "prices_ohlc", ["company_id"], unique=False)
    op.create_index(op.f("ix_prices_ohlc_date"), "prices_ohlc", ["date"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.String(length=50),
            nullable=False,
            comment="Snapshot type: full_analysis, fundamentals, technical, news",
        ),
        sa.Column(
            "version",
            sa.String(length=20),
            nullable=False,
            comment="Analysis version for tracking changes",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Complete analysis results",
        ),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Data provenance: APIs used, timestamps, versions",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshots_company_created", "snapshots", ["company_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_snapshots_company_id"), "snapshots", ["company_id"], unique=False)
    op.create_index("ix_snapshots_company_kind", "snapshots", ["company_id", "kind"], unique=False)
    op.create_index(op.f("ix_snapshots_created_at"), "snapshots", ["created_at"], unique=False)
    op.create_index(op.f("ix_snapshots_id"), "snapshots", ["id"], unique=False)
    op.create_index(op.f("ix_snapshots_kind"), "snapshots", ["kind"], unique=False)
    op.create_index("ix_snapshots_kind_created", "snapshots", ["kind", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshots_kind_created", table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_kind"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_id"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_created_at"), table_name="snapshots")
    op.drop_index("ix_snapshots_company_kind", table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_company_id"), table_name="snapshots")
    op.drop_index("ix_snapshots_company_created", table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_prices_ohlc_date"), table_name="prices_ohlc")
    op.drop_index(op.f("ix_prices_ohlc_company_id"), table_name="prices_ohlc")
    op.drop_index("ix_prices_date", table_name="prices_ohlc")
    op.drop_index("ix_prices_company_date", table_name="prices_ohlc")
    op.drop_table("prices_ohlc")
    op.drop_index(op.f("ix_financials_quarterly_quarter_date"), table_name="financials_quarterly")
    op.drop_index(op.f("ix_financials_quarterly_company_id"), table_name="financials_quarterly")
    op.drop_index("ix_financials_quarterly_company_date", table_name="financials_quarterly")
    op.drop_table("financials_quarterly")
    op.drop_index("ix_financials_year", table_name="financials_annual")
    op.drop_index("ix_financials_company_year", table_name="financials_annual")
    op.drop_index(op.f("ix_financials_annual_fiscal_year"), table_name="financials_annual")
    op.drop_index(op.f("ix_financials_annual_company_id"), table_name="financials_annual")
    op.drop_table("financials_annual")
    op.drop_index("ix_companies_symbol_sector", table_name="companies")
    op.drop_index(op.f("ix_companies_symbol"), table_name="companies")
    op.drop_index(op.f("ix_companies_sector"), table_name="companies")
    op.drop_index(op.f("ix_companies_isin"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
